/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Tracking {
      
    export type TypeShipmentStruct = {sender: AddressLike, receiver: AddressLike, pickupTime: BigNumberish, deliveryTime: BigNumberish, distance: BigNumberish, price: BigNumberish, status: BigNumberish, isPaid: boolean}

    export type TypeShipmentStructOutput = [sender: string, receiver: string, pickupTime: bigint, deliveryTime: bigint, distance: bigint, price: bigint, status: bigint, isPaid: boolean] & {sender: string, receiver: string, pickupTime: bigint, deliveryTime: bigint, distance: bigint, price: bigint, status: bigint, isPaid: boolean }
  
    }

  export interface TrackingInterface extends Interface {
    getFunction(nameOrSignature: "StartShipment" | "cancelShipment" | "completeShipment" | "createShipment" | "getAllTransactions" | "getShipment" | "getShipmentCount" | "shipmentCount" | "shipments" | "typeShipments"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ShipmentCancelled" | "ShipmentCreated" | "ShipmentDelivered" | "ShipmentInTransition" | "ShipmentPaid"): EventFragment;

    encodeFunctionData(functionFragment: 'StartShipment', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelShipment', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'completeShipment', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createShipment', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllTransactions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getShipment', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getShipmentCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'shipmentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'shipments', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'typeShipments', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'StartShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllTransactions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShipmentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shipmentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shipments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'typeShipments', data: BytesLike): Result;
  }

  
    export namespace ShipmentCancelledEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, pickupTime: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, pickupTime: bigint];
      export interface OutputObject {sender: string, receiver: string, pickupTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShipmentCreatedEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, pickupTime: BigNumberish, distance: BigNumberish, price: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, pickupTime: bigint, distance: bigint, price: bigint];
      export interface OutputObject {sender: string, receiver: string, pickupTime: bigint, distance: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShipmentDeliveredEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, deliveryTime: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, deliveryTime: bigint];
      export interface OutputObject {sender: string, receiver: string, deliveryTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShipmentInTransitionEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, pickupTime: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, pickupTime: bigint];
      export interface OutputObject {sender: string, receiver: string, pickupTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShipmentPaidEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, amount: bigint];
      export interface OutputObject {sender: string, receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Tracking extends BaseContract {
    
    connect(runner?: ContractRunner | null): Tracking;
    waitForDeployment(): Promise<this>;

    interface: TrackingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    StartShipment: TypedContractMethod<
      [_sender: AddressLike, _receiver: AddressLike, _index: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelShipment: TypedContractMethod<
      [_sender: AddressLike, _receiver: AddressLike, _index: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    completeShipment: TypedContractMethod<
      [_sender: AddressLike, _receiver: AddressLike, _index: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createShipment: TypedContractMethod<
      [_receiver: AddressLike, _pickupTime: BigNumberish, _distance: BigNumberish, _price: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getAllTransactions: TypedContractMethod<
      [],
      [Tracking.TypeShipmentStructOutput[]],
      'view'
    >
    

    
    getShipment: TypedContractMethod<
      [_sender: AddressLike, _index: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean]],
      'view'
    >
    

    
    getShipmentCount: TypedContractMethod<
      [_sender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    shipmentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    shipments: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {sender: string, receiver: string, pickupTime: bigint, deliveryTime: bigint, distance: bigint, price: bigint, status: bigint, isPaid: boolean }],
      'view'
    >
    

    
    typeShipments: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {sender: string, receiver: string, pickupTime: bigint, deliveryTime: bigint, distance: bigint, price: bigint, status: bigint, isPaid: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'StartShipment'): TypedContractMethod<
      [_sender: AddressLike, _receiver: AddressLike, _index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelShipment'): TypedContractMethod<
      [_sender: AddressLike, _receiver: AddressLike, _index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeShipment'): TypedContractMethod<
      [_sender: AddressLike, _receiver: AddressLike, _index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createShipment'): TypedContractMethod<
      [_receiver: AddressLike, _pickupTime: BigNumberish, _distance: BigNumberish, _price: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getAllTransactions'): TypedContractMethod<
      [],
      [Tracking.TypeShipmentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getShipment'): TypedContractMethod<
      [_sender: AddressLike, _index: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean]],
      'view'
    >;
getFunction(nameOrSignature: 'getShipmentCount'): TypedContractMethod<
      [_sender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'shipmentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'shipments'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {sender: string, receiver: string, pickupTime: bigint, deliveryTime: bigint, distance: bigint, price: bigint, status: bigint, isPaid: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'typeShipments'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {sender: string, receiver: string, pickupTime: bigint, deliveryTime: bigint, distance: bigint, price: bigint, status: bigint, isPaid: boolean }],
      'view'
    >;

    getEvent(key: 'ShipmentCancelled'): TypedContractEvent<ShipmentCancelledEvent.InputTuple, ShipmentCancelledEvent.OutputTuple, ShipmentCancelledEvent.OutputObject>;
getEvent(key: 'ShipmentCreated'): TypedContractEvent<ShipmentCreatedEvent.InputTuple, ShipmentCreatedEvent.OutputTuple, ShipmentCreatedEvent.OutputObject>;
getEvent(key: 'ShipmentDelivered'): TypedContractEvent<ShipmentDeliveredEvent.InputTuple, ShipmentDeliveredEvent.OutputTuple, ShipmentDeliveredEvent.OutputObject>;
getEvent(key: 'ShipmentInTransition'): TypedContractEvent<ShipmentInTransitionEvent.InputTuple, ShipmentInTransitionEvent.OutputTuple, ShipmentInTransitionEvent.OutputObject>;
getEvent(key: 'ShipmentPaid'): TypedContractEvent<ShipmentPaidEvent.InputTuple, ShipmentPaidEvent.OutputTuple, ShipmentPaidEvent.OutputObject>;

    filters: {
      
      'ShipmentCancelled(address,address,uint256)': TypedContractEvent<ShipmentCancelledEvent.InputTuple, ShipmentCancelledEvent.OutputTuple, ShipmentCancelledEvent.OutputObject>;
      ShipmentCancelled: TypedContractEvent<ShipmentCancelledEvent.InputTuple, ShipmentCancelledEvent.OutputTuple, ShipmentCancelledEvent.OutputObject>;
    

      'ShipmentCreated(address,address,uint256,uint256,uint256)': TypedContractEvent<ShipmentCreatedEvent.InputTuple, ShipmentCreatedEvent.OutputTuple, ShipmentCreatedEvent.OutputObject>;
      ShipmentCreated: TypedContractEvent<ShipmentCreatedEvent.InputTuple, ShipmentCreatedEvent.OutputTuple, ShipmentCreatedEvent.OutputObject>;
    

      'ShipmentDelivered(address,address,uint256)': TypedContractEvent<ShipmentDeliveredEvent.InputTuple, ShipmentDeliveredEvent.OutputTuple, ShipmentDeliveredEvent.OutputObject>;
      ShipmentDelivered: TypedContractEvent<ShipmentDeliveredEvent.InputTuple, ShipmentDeliveredEvent.OutputTuple, ShipmentDeliveredEvent.OutputObject>;
    

      'ShipmentInTransition(address,address,uint256)': TypedContractEvent<ShipmentInTransitionEvent.InputTuple, ShipmentInTransitionEvent.OutputTuple, ShipmentInTransitionEvent.OutputObject>;
      ShipmentInTransition: TypedContractEvent<ShipmentInTransitionEvent.InputTuple, ShipmentInTransitionEvent.OutputTuple, ShipmentInTransitionEvent.OutputObject>;
    

      'ShipmentPaid(address,address,uint256)': TypedContractEvent<ShipmentPaidEvent.InputTuple, ShipmentPaidEvent.OutputTuple, ShipmentPaidEvent.OutputObject>;
      ShipmentPaid: TypedContractEvent<ShipmentPaidEvent.InputTuple, ShipmentPaidEvent.OutputTuple, ShipmentPaidEvent.OutputObject>;
    
    };
  }